#!/bin/bash
program=${1:-"ss-server"}

export TOR_PT_MANAGED_TRANSPORT_VER=1
export TOR_PT_STATE_LOCATION=$OBFS4_CONFIG_DIR

case $program in
    ss-local | ss-redir | ss-tunnel)
        export TOR_PT_CLIENT_ADDR=$SS_SERVER_IP:$SS_SERVER_PORT
        export TOR_PT_TARGET=$OBFS4_SERVER_IP:$OBFS4_SERVER_PORT
        export TOR_PT_CLIENT_TRANSPORTS=obfs4
        export TOR_PT_CERT=$OBFS4_CERT
        ;;
    ss-server)
        export TOR_PT_SERVER_BINDADDR=obfs4-0.0.0.0:$OBFS4_SERVER_PORT
        export TOR_PT_ORPORT=$SS_SERVER_IP:$SS_SERVER_PORT
        export TOR_PT_SERVER_TRANSPORTS=obfs4
        ;;
    *)
        >&2 echo "[ERROR] unknown command: run $program"
        exit 1
        ;;
esac

if [[ $program == "ss-redir" ]]; then
    iptables -t nat -A PREROUTING -d $OBFS4_SERVER_IP -j RETURN
    iptables -t nat -A PREROUTING -d 0.0.0.0/8 -j RETURN
    iptables -t nat -A PREROUTING -d 10.0.0.0/8 -j RETURN
    iptables -t nat -A PREROUTING -d 127.0.0.0/8 -j RETURN
    iptables -t nat -A PREROUTING -d 169.254.0.0/16 -j RETURN
    iptables -t nat -A PREROUTING -d 172.16.0.0/12 -j RETURN
    iptables -t nat -A PREROUTING -d 192.168.0.0/16 -j RETURN
    iptables -t nat -A PREROUTING -d 224.0.0.0/4 -j RETURN
    iptables -t nat -A PREROUTING -d 240.0.0.0/4 -j RETURN
    iptables -t nat -A PREROUTING -p tcp -j REDIRECT --to-ports $SS_LOCAL_PORT
fi

obfs4proxy &
/usr/bin/$program -c /etc/shadowsocks-libev/config.json
